site_name: Colette
site_url: ""
site_author: Santtu Pesonen

use_directory_urls: false
plugins: []

theme:
  name: mkdocs
  color_mode: dark
  user_color_mode_toggle: true

nav:
 - 'Main page': index.md
 - 'Commands':
   - 'add': cmd/add.md
   - 'a(uto)rem(ove)': cmd/autoremove.md
   - 'clear': cmd/clear.md
   - 'edit': cmd/edit.md
   - 'exit': cmd/exit.md
   - 'help': cmd/help.md
   - 'list': cmd/list.md
   - 'rem(ove)': cmd/remove.md
   - 'search': cmd/search.md
   - 'sort': cmd/sort.md
   - 'ver(sion)': cmd/version.md
