site_name: Colette
site_url: ""
site_author: Santtu Pesonen

repo_url: https://github.com/MFG38/colette
edit_uri: tree/main/docs/

use_directory_urls: false
plugins: []

theme:
  name: mkdocs
  color_mode: auto
  user_color_mode_toggle: true

extra_css:
  - css/extra.css

nav:
  - 'Main page': index.md
  - 'User guide':
    - 'Installation': installation.md
    - 'Basic usage': basic_usage.md
    - 'Building Colette': building.md
  - 'Commands':
    - 'add': cmd/add.md
    - 'a(uto)rem(ove)': cmd/autoremove.md
    - 'clear': cmd/clear.md
    - 'complete/done': cmd/complete_done.md
    - 'debug': cmd/debug.md
    - 'edit': cmd/edit.md
    - 'exit/quit': cmd/exit_quit.md
    - 'help': cmd/help.md
    - 'list': cmd/list.md
    - 'rem(ove)': cmd/remove.md
    - 'search': cmd/search.md
    - 'sort': cmd/sort.md
    - 'test': cmd/test.md
    - 'ver(sion)': cmd/version.md
  - 'Technical details':
    - 'todo.clt breakdown': technical/todo_clt.md
    - 'Source code structure': technical/source_code_structure.md
